"""
Core data model for Adaptive Memory for Tutors.

Design intent (see docs/design_doc.md §4):
- ConceptPair and ConfusionEvent are what integrators send us.
- InsightLog is what we hand back. It may eventually be derived directly
  from Graphiti edge invalidation (valid_at/invalid_at) rather than stored
  separately -- left as a TODO for whoever builds insight_engine.py further,
  see the note there.
- student_ref is intentionally opaque. We never require or store real
  student PII -- the integrating tutor owns that mapping.
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ConceptPair(BaseModel):
    id: str
    tenant_id: str
    domain: str  # e.g. "japanese-kana", "chemistry-notation"
    label_a: str
    label_b: str
    description: Optional[str] = None


class ConfusionEvent(BaseModel):
    """One observed instance of a student getting a concept-pair question
    right or wrong. This is what gets sent to Zep as an episode."""

    tenant_id: str
    pair_id: str
    student_ref: str  # opaque integrator-supplied identifier, never real PII
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    correct: bool
    context: Optional[str] = None  # free text, e.g. "confused at end of word"


class InsightDecision(str, Enum):
    ESCALATE = "escalate"      # confusion persisting / worsening -> drill more
    RETIRE = "retire"          # resolved -> stop actively drilling
    NO_CHANGE = "no_change"    # not enough signal yet to change strategy


class InsightLog(BaseModel):
    tenant_id: str
    pair_id: str
    student_ref: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    decision: InsightDecision
    reasoning: str  # one-line, human-readable, generated by the insight engine
